package com.zy.bk.mapper;

import com.zy.bk.entity.ArticleTag;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ArticleTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article_tag
     *
     * @mbggenerated Fri Mar 03 10:25:35 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article_tag
     *
     * @mbggenerated Fri Mar 03 10:25:35 CST 2023
     */
    int insert(ArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article_tag
     *
     * @mbggenerated Fri Mar 03 10:25:35 CST 2023
     */
    int insertSelective(ArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article_tag
     *
     * @mbggenerated Fri Mar 03 10:25:35 CST 2023
     */
    ArticleTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article_tag
     *
     * @mbggenerated Fri Mar 03 10:25:35 CST 2023
     */
    int updateByPrimaryKeySelective(ArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article_tag
     *
     * @mbggenerated Fri Mar 03 10:25:35 CST 2023
     */
    int updateByPrimaryKey(ArticleTag record);
}