package com.zy.bk.mapper;

import com.zy.bk.entity.MsSysUser;

public interface MsSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_sys_user
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_sys_user
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    int insert(MsSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_sys_user
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    int insertSelective(MsSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_sys_user
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    MsSysUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_sys_user
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    int updateByPrimaryKeySelective(MsSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_sys_user
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    int updateByPrimaryKey(MsSysUser record);
}