package com.zy.bk.entity;

public class MsArticle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_article.id
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_article.comment_counts
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    private Integer commentCounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_article.create_date
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    private Long createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_article.summary
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_article.title
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_article.view_counts
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    private Integer viewCounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_article.weight
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_article.author_id
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    private Long authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_article.body_id
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    private Long bodyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_article.category_id
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    private Integer categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_article.id
     *
     * @return the value of ms_article.id
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_article.id
     *
     * @param id the value for ms_article.id
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_article.comment_counts
     *
     * @return the value of ms_article.comment_counts
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public Integer getCommentCounts() {
        return commentCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_article.comment_counts
     *
     * @param commentCounts the value for ms_article.comment_counts
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public void setCommentCounts(Integer commentCounts) {
        this.commentCounts = commentCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_article.create_date
     *
     * @return the value of ms_article.create_date
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public Long getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_article.create_date
     *
     * @param createDate the value for ms_article.create_date
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_article.summary
     *
     * @return the value of ms_article.summary
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_article.summary
     *
     * @param summary the value for ms_article.summary
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_article.title
     *
     * @return the value of ms_article.title
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_article.title
     *
     * @param title the value for ms_article.title
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_article.view_counts
     *
     * @return the value of ms_article.view_counts
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public Integer getViewCounts() {
        return viewCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_article.view_counts
     *
     * @param viewCounts the value for ms_article.view_counts
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public void setViewCounts(Integer viewCounts) {
        this.viewCounts = viewCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_article.weight
     *
     * @return the value of ms_article.weight
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_article.weight
     *
     * @param weight the value for ms_article.weight
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_article.author_id
     *
     * @return the value of ms_article.author_id
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public Long getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_article.author_id
     *
     * @param authorId the value for ms_article.author_id
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_article.body_id
     *
     * @return the value of ms_article.body_id
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public Long getBodyId() {
        return bodyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_article.body_id
     *
     * @param bodyId the value for ms_article.body_id
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public void setBodyId(Long bodyId) {
        this.bodyId = bodyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_article.category_id
     *
     * @return the value of ms_article.category_id
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_article.category_id
     *
     * @param categoryId the value for ms_article.category_id
     *
     * @mbggenerated Fri Mar 03 10:24:15 CST 2023
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
}