package com.zy.bk.entity;

public class MsArticleTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_article_tag.id
     *
     * @mbggenerated Fri Mar 03 10:25:35 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_article_tag.article_id
     *
     * @mbggenerated Fri Mar 03 10:25:35 CST 2023
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_article_tag.tag_id
     *
     * @mbggenerated Fri Mar 03 10:25:35 CST 2023
     */
    private Long tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_article_tag.id
     *
     * @return the value of ms_article_tag.id
     *
     * @mbggenerated Fri Mar 03 10:25:35 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_article_tag.id
     *
     * @param id the value for ms_article_tag.id
     *
     * @mbggenerated Fri Mar 03 10:25:35 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_article_tag.article_id
     *
     * @return the value of ms_article_tag.article_id
     *
     * @mbggenerated Fri Mar 03 10:25:35 CST 2023
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_article_tag.article_id
     *
     * @param articleId the value for ms_article_tag.article_id
     *
     * @mbggenerated Fri Mar 03 10:25:35 CST 2023
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_article_tag.tag_id
     *
     * @return the value of ms_article_tag.tag_id
     *
     * @mbggenerated Fri Mar 03 10:25:35 CST 2023
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_article_tag.tag_id
     *
     * @param tagId the value for ms_article_tag.tag_id
     *
     * @mbggenerated Fri Mar 03 10:25:35 CST 2023
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }
}