package com.zy.bk.entity;

public class MsSysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_sys_user.id
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_sys_user.account
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_sys_user.admin
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    private Boolean admin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_sys_user.avatar
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_sys_user.create_date
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    private Long createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_sys_user.deleted
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_sys_user.email
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_sys_user.last_login
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    private Long lastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_sys_user.mobile_phone_number
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    private String mobilePhoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_sys_user.nickname
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_sys_user.password
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_sys_user.salt
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_sys_user.status
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_sys_user.id
     *
     * @return the value of ms_sys_user.id
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_sys_user.id
     *
     * @param id the value for ms_sys_user.id
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_sys_user.account
     *
     * @return the value of ms_sys_user.account
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_sys_user.account
     *
     * @param account the value for ms_sys_user.account
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_sys_user.admin
     *
     * @return the value of ms_sys_user.admin
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public Boolean getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_sys_user.admin
     *
     * @param admin the value for ms_sys_user.admin
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_sys_user.avatar
     *
     * @return the value of ms_sys_user.avatar
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_sys_user.avatar
     *
     * @param avatar the value for ms_sys_user.avatar
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_sys_user.create_date
     *
     * @return the value of ms_sys_user.create_date
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public Long getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_sys_user.create_date
     *
     * @param createDate the value for ms_sys_user.create_date
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_sys_user.deleted
     *
     * @return the value of ms_sys_user.deleted
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_sys_user.deleted
     *
     * @param deleted the value for ms_sys_user.deleted
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_sys_user.email
     *
     * @return the value of ms_sys_user.email
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_sys_user.email
     *
     * @param email the value for ms_sys_user.email
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_sys_user.last_login
     *
     * @return the value of ms_sys_user.last_login
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public Long getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_sys_user.last_login
     *
     * @param lastLogin the value for ms_sys_user.last_login
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public void setLastLogin(Long lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_sys_user.mobile_phone_number
     *
     * @return the value of ms_sys_user.mobile_phone_number
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public String getMobilePhoneNumber() {
        return mobilePhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_sys_user.mobile_phone_number
     *
     * @param mobilePhoneNumber the value for ms_sys_user.mobile_phone_number
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public void setMobilePhoneNumber(String mobilePhoneNumber) {
        this.mobilePhoneNumber = mobilePhoneNumber == null ? null : mobilePhoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_sys_user.nickname
     *
     * @return the value of ms_sys_user.nickname
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_sys_user.nickname
     *
     * @param nickname the value for ms_sys_user.nickname
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_sys_user.password
     *
     * @return the value of ms_sys_user.password
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_sys_user.password
     *
     * @param password the value for ms_sys_user.password
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_sys_user.salt
     *
     * @return the value of ms_sys_user.salt
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_sys_user.salt
     *
     * @param salt the value for ms_sys_user.salt
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_sys_user.status
     *
     * @return the value of ms_sys_user.status
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_sys_user.status
     *
     * @param status the value for ms_sys_user.status
     *
     * @mbggenerated Fri Mar 03 10:26:59 CST 2023
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}